### ISSUE TITLE
Allow `.` to separate dynamic segments

### ISSUE THREAD

**Issue by seanmonstar** [http-rs/route-recognizer#16]
This blocks being able to make a route like `/crates/:crate_id.svg`

**Comment by Parakleta** [comment]
I think I'd prefer this to use a generic glob rather than be restricted to only file extensions.  Something like `/crates/:crate_id:*.svg`.  All of the generic globbing rules (`*`, `?`, `[abc]`, `[a-z]`, `[!abc]`, `[!a-z]`) are easy to support with the existing `nfa.rs` architecture (in fact everything but `[a-z]` and `[!a-z]` is already supported).

**Comment by stepankuzmin** [comment]
Any news on that?
