### ISSUE TITLE
Percent-encoded paths are not handled correctly

### ISSUE THREAD

**Issue by malaire** [http-rs/route-recognizer#44]
Here's two failing examples:
```rust
use route_recognizer::Router;

fn main() {
    let mut router = Router::new();
    router.add("/foo%2Fbar", "Hello".to_string());
    router.add("/foo bar", "Hello".to_string());

    assert_eq!(
        router.recognize("/foo%2fbar").unwrap().handler().as_str(),
        "Hello"
    );

    assert_eq!(
        router.recognize("/foo%20bar").unwrap().handler().as_str(),
        "Hello"
    );
}
```

**Comment by yoshuawuyts** [comment]
I'm not entirely sure whether this is a bug since we don't advertise that we support percent-encoding anywhere, but I think it's fair to expect this would work. Especially since `http_types::Url`  parses `foo bar` as `foo%20` bar:

```rust
    use url::Url;
    let url = Url::parse("https://foo.com/ bar").unwrap();
    assert_eq!(url.path(), "/%20bar");
```

cc/ @mendelt you recently did work on parsing string-decoded params in Tide. This seems like another variant on that, but at the router layer. Do you have any opinions on what we should do here?

**Comment by mendelt** [comment]
Not sure. I like how the route-recognizer is a crate that does one thing well. Adding this on top seems like a bit of scope-creep. Especially since there is another crate that does percent-encoding/decoding pretty well (https://crates.io/crates/percent-encoding). I'd say it's up to the calling code to compose those two crates together.

Route-recognizer also seems set up to be a bit more generic than just url-parsing? But I can't really think of any other use-cases than parsing urls? Maybe parsing paths? Adding percent-decoding really ties it to the url-use-case.

But on the other hand, I can also imagine you don't want to force all the crates that depend on the route-recognizer to re-invent the wheel? I wouldn't really be opposed to porting over https://github.com/http-rs/tide/pull/757 to the route-recognizer.

**Comment by malaire** [comment]
> So adding percent-decoding to route-recognizer will just be a simple call to the percent-encoding crate

I'm not convinced it's that simple. There are edge cases to consider, for example `%2f` and `%2F` match each other but not `/`, and so `%2f` and `%2F` must not be decoded until path has been split into segments. Decoding unsplit path like `/foo%2fbar/baz` leads to wrong behavior.

On the other hand some characters do have three representations, for example `%7e`, `%7E` and `~` all match each other.

Also at all times one must know whether a string has been decoded/encoded to avoid double-encoding/decoding.

**Comment by mendelt** [comment]
Ah, sorry, I only now read the original issue carefully. What you're proposing is a bit different than what my Tide pr is doing. I'm only decoding parsed parameters, you're proposing to have matching work on decoded paths.
> Decoding unsplit path like `/foo%2fbar/baz` leads to wrong behavior.
Agreed, we should not decode the whole url and then match. Matching should be done after splitting

> On the other hand some characters do have three representations, for example %7e, %7E and ~ all match each other.
It's true that they decode to the same character. Not sure if that means they should match each other. To me this would be unexpected behaviour to be honest. In my mind `http://example.com/some~url`, `http://example.com/some%7Eurl` and `http://example.com/some%7eurl` are different urls, and I would have been surprised to find out they would match the same route. 

But I guess matching on the raw urls is my personal preference. I can imagine we'd want to go your way. If we do want the matching to work on decoded urls the logical place to do this would be inside `route-recognizer`

> Also at all times one must know whether a string has been decoded/encoded to avoid double-encoding/decoding.
thats a good one. If I look at your example above:
```
    assert_eq!(
        router.recognize("/foo%2fbar").unwrap().handler().as_str(),
        "Hello"
    );

    assert_eq!(
        router.recognize("/foo%20bar").unwrap().handler().as_str(),
        "Hello"
    );
```
I would not expect these to work at all. Why allow specifying routes as encoded strings if we want matching to work on decoded strings. I think we should specify routes as decoded strings right? So `router.recognize("/foo%20bar")` should not match but `router.recognize("/foo bar")` should. Otherwise you're mixing up encoded and decoded.

**Comment by malaire** [comment]
> It's true that they decode to the same character. Not sure if that means they should match each other. Percent encoding is not much of a standard to begin with but I'm pretty sure it says nothing about matching urls. To me this would be unexpected behaviour to be honest. In my mind `http://example.com/some~url`, `http://example.com/some%7Eurl` and `http://example.com/some%7eurl` are different urls, and I would have been surprised to find out they would match the same route.

[RFC 3986](https://tools.ietf.org/html/rfc3986) says that **those three are equivalent** so your expectations are contrary to the URI standard.

Some relevant parts from RFC 3986:

* 2.3.  Unreserved Characters
> URIs that differ in the replacement of an unreserved character with its corresponding percent-encoded US-ASCII octet are equivalent: they identify the same resource.  However, URI comparison implementations do not always perform normalization prior to comparison (see Section 6).  For consistency, percent-encoded octets in the ranges of ALPHA (%41-%5A and %61-%7A), DIGIT (%30-%39), hyphen (%2D), period (%2E), underscore (%5F), or tilde (%7E) should not be created by URI producers and, when found in a URI, should be decoded to their corresponding unreserved characters by URI normalizers.

* 6.2.2.1. Case Normalization
> For all URIs, the hexadecimal digits within a percent-encoding triplet (e.g., "%3a" versus "%3A") are case-insensitive and therefore should be normalized to use uppercase letters for the digits A-F.

* 6.2.2.2.  Percent-Encoding Normalization
> The percent-encoding mechanism (Section 2.1) is a frequent source of variance among otherwise identical URIs.  In addition to the case normalization issue noted above, some URI producers percent-encode octets that do not require percent-encoding, resulting in URIs that are equivalent to their non-encoded counterparts.  These URIs should be normalized by decoding any percent-encoded octet that corresponds to an unreserved character, as described in Section 2.3.

**Comment by malaire** [comment]
> I think we should specify routes as decoded strings right?

Path `"/foo%2fbar"` can't be represented as decoded string because `"/foo/bar"`is **different** path.

**Comment by mendelt** [comment]
> says that those three are equivalent so your expectations are contrary to the URI standard.

Ok, that makes sense. If those three URLs need to resolve to the same resource then the easiest way to do that is to do it inside this crate I guess.

So I think the right way to do this would be to first split up incoming urls, then url-decode the segments. We'll need to do the same with the specified routes I guess. I still find this a bit unfortunate. I'd rather specify routes in their decoded form. That makes it clear to a user that that's how they are matched. We really need to document that well.
If we first split, then decode for both the routes and incoming urls that should handle `2F`, `2f` and `/` correctly. Is there anything specific we need to do for `~` and `7e`?

**Comment by malaire** [comment]
Sorry, I forgot that RFC isn't latest standard, latest is http://url.spec.whatwg.org/
I'll try to read this tomorrow to see if anything has changed, but it is quite a bit move involved.

**Comment by malaire** [comment]
Given the complexity of URL standard, URL parsing should really be done in a specialized crate. Crate `url` says that it follows the URL standard, but it doesn't serialize `%7e` to `~` as I understand it should, so I opened an issue there to clarify what is correct behavior: https://github.com/servo/rust-url/issues/664

**Comment by malaire** [comment]
I got answer from WHATWG member in issue https://github.com/whatwg/url/issues/565 and it looks like I was wrong here: Current URL spec differs drastically from older RFC 3986 in how such URLs should be handled. According to current spec percent-decoding is **not** done for URLs when determining whether URLs are equivalent.

**Comment by mendelt** [comment]
Thank you for figuring this out for us. It's a bit of a surprise to me but makes our life a lot easier I guess.
